include:
  - project: 'zl0i/gitlab-ci-template'
    ref: main
    file: 'build.template.yaml'
  - project: 'zl0i/gitlab-ci-template'
    ref: main
    file: 'release.template.yaml'
  - template: Code-Quality.gitlab-ci.yml

stages:
  - test
  - build
  - deploy
  - release

code_quality:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test:
  image: node:16.13.2-alpine
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules/
  before_script:
    - npm ci
  script:
    - npm run test

build:
  extends: .kaniko
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    IMAGE_NAME: $CI_PROJECT_NAME
    IMAGE_TAG: $CI_COMMIT_TAG

deploy:
  stage: deploy
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    GIT_STRATEGY: none
  script:
    - crane auth login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - crane auth login docker.io -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - crane cp $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_TAG docker.io/zl0i/$CI_PROJECT_NAME:$CI_COMMIT_TAG
    - crane cp $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_TAG docker.io/zl0i/$CI_PROJECT_NAME:latest
