include:
  - project: 'zl0i/gitlab-ci-template'
    ref: main
    file: 'build.template.yaml'
  - template: Code-Quality.gitlab-ci.yml

stages:
  - test
  - build

code_quality:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test:
  image: node:16.13.2-alpine
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules/
  before_script:
    - npm ci
  script:
    - npm run test

build:
  extends: .kaniko
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    IMAGE_NAME: alertmanager-matrix-forwarder
    IMAGE_TAG: $CI_COMMIT_TAG
